android.useAndroidX=true
# increase heap and metaspace for Gradle daemon (better stability on Kotlin/Compose Builds)
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
# kotlin.daemon.jvmargs=...
android.suppressUnsupportedCompileSdk=35
org.gradle.configuration-cache=true
org.gradle.java.home=/Library/Java/JavaVirtualMachines/microsoft-25.jdk/Contents/Home
org.gradle.parallel=true
org.gradle.caching=true

